name: Testing-for-approvals

on:
  push:
    branches:
      -  main
    
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      
  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - name: Run the build command
        run: echo "Build prod"
