name: Testing-for-approvals

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy"
        required: true
        type: choice
        options:
          - dev
          - prod
    
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      
  deploy-dev:
    runs-on: ubuntu-latest
    needs: build-and-publish
    steps:
      - name: echo command
        run: |
          echo "deploy to the environment: ${{ github.event.input.environment.dev }}"

  deploy-prod:
    runs-on: ubuntu-latest
    environment:
      name: 'prod'
    needs: [build-and-publish, deploy-dev]
    steps:
      - name: echo file
        run: |
          echo "deploy to the environment:${{ github.event.input.environment.prod }}"
