name: Testing-for-approvals

on:
  push:
    branches:
      - "main"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      
  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: 'dev'
    needs: build-and-publish
    steps:
      - name: echo command
        run: echo "Hello world"

  deploy-prod:
    runs-on: ubuntu-latest
    environment:
      name: 'prod'
    needs: [build-and-publish, deploy-dev]
    steps:
      - name: echo file
        run: echo "Hello world" > hello.txt 
