name: Testing-for-approvals

on:
  push:
    branches:
      -  main
    
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

# Here we have given the environment because the same environment we have updated inside and inside the setting we have updated into the environment as secret.
 
  deploy-prod:
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - name: Run the build command
        run: echo "Build prod"

  build-with-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps: 
      - name: Run the build command for dev env
        run: echo "Build Dev"

        
